# Generated by Django 4.1.7 on 2023-03-20 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='full_desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
